const IDLE:  [&str;172] = ["cached session",                                              
"VKTM Logical Idle Wait",                                      
"VKTM Init Wait for GSGA",                                     
"IORM Scheduler Slave Idle Wait",                              
"rdbms ipc message",                                           
"i/o slave wait",                                              
"OFS Receive Queue",                                           
"OFS idle",                                                    
"Generic Process Pool Dispatcher: idle",                       
"Generic Process Pool Worker: sleep",                          
"VKRM Idle",                                                   
"wait for unread message on broadcast channel",                
"wait for unread message on multiple broadcast channels",      
"class slave wait",                                            
"idle class spare wait event 1",                               
"idle class spare wait event 2",                               
"idle class spare wait event 3",                               
"idle class spare wait event 4",                               
"idle class spare wait event 5",                               
"idle class spare wait event 6",                               
"idle class spare wait event 7",                               
"idle class spare wait event 8",                               
"idle class spare wait event 9",                               
"idle class spare wait event 10",                              
"RMA: IPC0 completion sync",                                   
"PING",                                                        
"spawn request deferred",                                      
"watchdog main loop",                                          
"process in prespawned state",                                 
"pmon timer",                                                  
"pman timer",                                                  
"DNFS disp IO slave idle",                                     
"NVM disp IO slave idle",                                      
"BRDG: bridge controller idle",                                
"Network Retrans by Server",                                   
"Network Retrans by Client",                                   
"Distributed Trace: Archival Worker Idle",                     
"DIAG idle wait",                                              
"ges remote message",                                          
"SCM slave idle",                                              
"LMS CR slave timer",                                          
"gcs remote message",                                          
"gcs yield cpu",                                               
"heartbeat monitor sleep",                                     
"GCR sleep",                                                   
"Shutdown completion due to error",                            
"SGA: MMAN sleep for component shrink",                        
"DBWR timer",                                                  
"Data Guard: Gap Manager",                                     
"Data Guard: controlfile update",                              
"MRP redo arrival",                                            
"Data Guard: Timer",                                           
"LNS ASYNC archive log",                                       
"LNS ASYNC dest activation",                                   
"LNS ASYNC end of log",                                        
"Archiver: redo logs",                                         
"simulated log write delay",                                   
"heartbeat redo informer",                                     
"LGWR real time apply sync",                                   
"LGWR worker group idle",                                      
"parallel recovery slave idle wait",                           
"Backup Appliance waiting for work",                           
"Backup Appliance waiting restore start",                      
"Backup Appliance Surrogate wait",                             
"Backup Appliance Servlet wait",                               
"Backup Appliance Comm SGA setup wait",                        
"LogMiner builder: idle",                                      
"LogMiner builder: branch",                                    
"LogMiner preparer: idle",                                     
"LogMiner reader: log (idle)",                                 
"LogMiner reader: redo (idle)",                                
"LogMiner merger: idle",                                       
"LogMiner client: transaction",                                
"LogMiner: other",                                             
"LogMiner: activate",                                          
"LogMiner: reset",                                             
"LogMiner: find session",                                      
"LogMiner: internal",                                          
"Logical Standby Apply Delay",                                 
"parallel recovery coordinator waits for slave cleanup",       
"parallel recovery coordinator idle wait",                     
"parallel recovery control message reply",                     
"parallel recovery slave next change",                         
"nologging fetch slave idle",                                  
"recovery sender idle",                                        
"recovery receiver idle",                                      
"recovery coordinator idle",                                   
"recovery logmerger idle",                                     
"block compare coord process idle",                            
"Data Guard PDB query SCN service idle",                       
"True Cache: background process idle",                         
"PX Deq: Txn Recovery Start",                                  
"PX Deq: Txn Recovery Reply",                                  
"fbar timer",                                                  
"smon timer",                                                  
"PX Deq: Metadata Update",                                     
"Space Manager: slave idle wait",                              
"PX Deq: Index Merge Reply",                                   
"PX Deq: Index Merge Execute",                                 
"PX Deq: Index Merge Close",                                   
"PX Deq: kdcph_mai",                                           
"PX Deq: kdcphc_ack",                                          
"imco timer",                                                  
"IMFS defer writes scheduler",                                 
"memoptimize write drain idle",                                
"MLE sleep",                                                   
"virtual circuit next request",                                
"shared server idle wait",                                     
"dispatcher timer",                                            
"cmon timer",                                                  
"pool server timer",                                           
"lreg timer",                                                  
"JOX Jit Process Sleep",                                       
"jobq slave wait",                                             
"pipe get",                                                    
"PX Deque wait",                                               
"PX Idle Wait",                                                
"PX Deq Credit: need buffer",                                  
"PX Deq Credit: send blkd",                                    
"PX Deq: Msg Fragment",                                        
"PX Deq: Parse Reply",                                         
"PX Deq: Execute Reply",                                       
"PX Deq: Execution Msg",                                       
"PX Deq: Table Q Normal",                                      
"PX Deq: Table Q Sample",                                      
"REPL Apply: txns",                                            
"REPL Capture/Apply: messages",                                
"REPL Capture: archive log",                                   
"single-task message",                                         
"SQL*Net message from client",                                 
"SQL*Net vector message from client",                          
"SQL*Net vector message from dblink",                          
"PL/SQL lock timer",                                           
"Streams AQ: emn coordinator idle wait",                       
"EMON slave idle wait",                                        
"Emon coordinator main loop",                                  
"Emon slave main loop",                                        
"Streams AQ: waiting for messages in the queue",               
"Streams AQ: waiting for time management or cleanup tasks",    
"Streams AQ: delete acknowledged messages",                    
"Streams AQ: deallocate messages from Streams Pool",           
"Streams AQ: qmn coordinator idle wait",                       
"Streams AQ: qmn slave idle wait",                             
"AQ: 12c message cache init wait",                             
"AQ Cross Master idle",                                        
"AQPC idle",                                                   
"Streams AQ: load balancer idle",                              
"Sharded  Queues : Part Maintenance idle",                     
"Sharded  Queues : Part Truncate idle",                        
"REPL Capture/Apply: RAC AQ qmn coordinator",                  
"Streams AQ: opt idle",                                        
"HS message to agent",                                         
"ASM background timer",                                        
"ASM cluster membership changes",                              
"AUTO access ASM_CLIENT registration",                         
"iowp msg",                                                    
"iowp file id",                                                
"netp network",                                                
"gopp msg",                                                    
"auto-sqltune: wait graph update",                             
"WCR: replay client notify",                                   
"WCR: replay clock",                                           
"WCR: replay paused",                                          
"JS external job",                                             
"cell worker idle",                                            
"Multi-Tenant Redo File Server - Flush Header Interval",       
"Sharding replication",                                        
"Consensus service idle",                                      
"Blockchain apply clean",                                      
"blockchain apply short",                                      
"blockchain apply long",                                       
"Blockchain reader process idle"];

pub fn is_idle(event_name: &str) -> bool {
    for event in IDLE {
        if event.starts_with(event_name) {
            return true;
        }
    }
    false
}